### ISSUE TITLE
TPS laser weapon part data

### ISSUE THREAD

**Issue by LukeParlin** [apple1417/bl2.parts#6]
I realize that the site is called **bl2**.parts, but seeing as you've already got part data from The Pre-Sequel in the other weapon/gear categories, is there any chance you could add TPS laser weapon part data to the site?

I aknowledge this requires time/work, but I hoped that it couldn't hurt to ask! Thanks for the work you've done to create and maintain the site regardless 🙏

**Comment by apple1417** [comment]
It's actually already there. https://bl2.parts/lasers/all_parts/ and https://bl2.parts/launchers/all_parts/ both exist, I just haven't had the time to cut out some nice pictures for the base guides.
