### ISSUE TITLE
Where are the rocket launchers?

### ISSUE THREAD

**Issue by williampearcedev** [apple1417/bl2.parts#7]
You don't have a section for the launcher parts, please add them. Otherwise this is very helpful!

**Comment by apple1417** [comment]
https://bl2.parts/lasers/all_parts/ and https://bl2.parts/launchers/all_parts/ both already existed, just haven't had the time/will to go cut out all the pictures for the base guides. You're not the first to ask though, so I've put them in the sidebar despite being incomplete.
